# Site settings
title: Len Strnad
email: ljstrnadiii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Science, Trail Running and Mountain Stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  ljstrnadiii

# Build settings
markdown: kramdown
highlighter: rouge

# Other options
permalink: blog/:year/:month/:title
job.title: "Machine Learning Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: "ljstrnadiii"
# google_site_verification: ""
# bing_webmastertools_id: ""
